### ISSUE TITLE
后台服务启动报错

### ISSUE THREAD

**Issue by nanfenghuiyi** [vis-three/scene-editor-service#4]
![image](https://github.com/vis-three/scene-editor-service/assets/51777595/c283d35c-19e1-4aa6-902f-ca5b45c13851)

**Comment by Shiotsukikaedesari** [comment]
此issue已归类为“提问”标签，请进入赞助、合作、通知群进行 issue 完成度与回报模式确认，QQ：586362945，详细issue流程请参照README.md。

**Comment by Shiotsukikaedesari** [comment]
一般不会出现这个问题，不管是3.0分支还是master分支，因为服务在启动的时候会自动补全不存在的文件夹。
尝试修复：
1、去到报错路径位置，查看文件夹是否存在
2、不存在就手动创建
