### ISSUE TITLE
后台启动不起来，使用npm run start报错resources\app不存在

### ISSUE THREAD

**Issue by tgy3300** [vis-three/scene-editor-service#5]
把项目git后，使用npm i安装依赖，然后再使用npm run start启动项目，报错如下：
`display-service@0.6.10 start
> nest start

[Nest] 4616  - 2023/10/13 12:25:42     LOG [NestFactory] Starting Nest application...
[Nest] 4616  - 2023/10/13 12:25:42     LOG [InstanceLoader] TypeOrmModule dependencies initialized +128ms
[Nest] 4616  - 2023/10/13 12:25:42     LOG [InstanceLoader] MulterModule dependencies initialized +1ms
[Nest] 4616  - 2023/10/13 12:25:42     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 4616  - 2023/10/13 12:25:42     LOG [InstanceLoader] MulterModule dependencies initialized +1ms
[Nest] 4616  - 2023/10/13 12:25:42     LOG [InstanceLoader] MulterModule dependencies initialized +0ms
[Nest] 4616  - 2023/10/13 12:25:42     LOG [InstanceLoader] CacheModule dependencies initialized +1ms
[Nest] 4616  - 2023/10/13 12:25:42     LOG [FileService] USER_PATH --> F:\zlserve-project\demo\scene-editor\scene-editor-service\resources\user
[Nest] 4616  - 2023/10/13 12:25:42     LOG [FileService] PLATFORM_PATH --> F:\zlserve-project\demo\scene-editor\scene-editor-service\resources\platform
[Nest] 4616  - 2023/10/13 12:25:42     LOG [FileService] COMMUNITY_PATH --> F:\zlserve-project\demo\scene-editor\scene-editor-service\resources\community
[Nest] 4616  - 2023/10/13 12:25:42     LOG [InstanceLoader] FileModule dependencies initialized +2ms
Error: ENOENT: no such file or directory, mkdir 'F:\zlserve-project\demo\scene-editor\scene-editor-service\resources\app'`

查看，确定没有resources\app，这个如何解决呀

**Comment by Shiotsukikaedesari** [comment]
#4
